version: '2'
volumes:
  data-mysql:
    driver: 'local'
services:
  mysql:
    image: mysql
    volumes:
      - data-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password